# Generated by Django 3.0 on 2020-06-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Services',
        ),
    ]
