# Generated by Django 3.0 on 2020-06-09 06:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200608_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.service_image_file_path),
        ),
    ]
